import { ArrowUpRight, ShieldCheck, FileSearch, KeyRound, Landmark, Check, MapPin, Mail } from 'lucide-react';
const services = [
  { icon: FileSearch, name: 'Title research', copy: 'A closer look at property records, ownership history, and the details that matter to your transaction.' },
  { icon: ShieldCheck, name: 'Title insurance', copy: 'Guidance on title protection for buyers and lenders, with clear explanations along the way.' },
  { icon: KeyRound, name: 'Closing & settlement', copy: 'Thoughtful coordination of documents, signatures, and the steps that bring your transaction together.' },
  { icon: Landmark, name: 'Refinance transactions', copy: 'Title and settlement support for homeowners and lending partners taking the next financial step.' },
];
const links = [['Services', '#services'], ['Our company', '#company'], ['Service area', '#service-area']];
export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><div className="container nav">
      <a className="brand" href="#" aria-label="Preferred Title Company home"><span className="brand-mark">P<span>.</span></span><span className="brand-type">PREFERRED<span>TITLE COMPANY LLC</span></span></a>
      <nav className="desktop-nav" aria-label="Main navigation">{links.map(([title, href]) => <a key={href} href={href}>{title}</a>)}</nav>
      <a className="nav-contact" href="#contact">Let’s connect <ArrowUpRight size={17}/></a>
      <details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation">{links.map(([title, href]) => <a key={href} href={href}>{title}</a>)}<a href="#contact">Contact us</a></nav></details>
    </div></header>
    <main id="main">
      <section className="hero container">
        <div className="hero-copy"><p className="eyebrow"><span/> YOUR NEW JERSEY TITLE PARTNER</p><h1>Your next chapter.<br/>Our attention<br/>to <em>every detail.</em></h1><p className="intro">Real estate is personal. Your closing should feel that way, too. Move forward with clarity and confidence with Preferred Title Company LLC.</p><div className="hero-actions"><a className="button primary" href="#contact">Let’s talk about your closing <ArrowUpRight size={19}/></a><a className="text-link" href="#services">Explore our services <span>↓</span></a></div><div className="hero-note"><ShieldCheck size={22}/><span>Careful preparation. Clear communication.</span></div></div>
        <div className="hero-visual"><img src="/home.jpg" alt="White home with a welcoming front entrance and a green lawn" width="1600" height="1067" fetchPriority="high"/><div className="image-label"><span>THE FOUNDATION OF WHAT’S NEXT</span><p>More than a property.<br/>A place to begin.</p></div><span className="corner-label">PREFERRED TITLE COMPANY LLC</span></div>
      </section>
      <div className="principles"><div className="container principle-grid">{['All 21 New Jersey counties', 'Details that matter', 'Clarity at every step'].map(item => <span key={item}><Check size={18}/>{item}</span>)}</div></div>
      <section className="section container" id="services"><div className="section-heading"><div><p className="eyebrow">01 / OUR SERVICES</p><h2>Expert care for<br/>your next move.</h2></div><p>From the first question to the final signature, a thoughtful approach to the title and closing process.</p></div><div className="services-grid">{services.map(({icon: Icon,name,copy}, index) => <article className="service" key={name}><div className="service-top"><Icon size={29} strokeWidth={1.4}/><span>0{index+1}</span></div><h3>{name}</h3><p>{copy}</p></article>)}</div></section>
      <section className="company section" id="company"><div className="container company-grid"><div><p className="eyebrow">02 / THE PREFERRED DIFFERENCE</p><h2>A company built<br/>around <em>your confidence.</em></h2><div className="company-signature">Preferred Title Company LLC<span>PERSONAL SERVICE. PURPOSEFUL ATTENTION.</span></div></div><div className="company-copy"><p className="large-copy">Behind every property is a person, a plan, and a new possibility.</p><p>As a family-founded venture, we’re building Preferred Title Company LLC around a simple idea: people deserve to understand their transaction and feel supported throughout it.</p><p>Our approach puts careful preparation and straightforward communication at the center of the experience—for buyers, sellers, real estate professionals, and lending partners.</p><a className="text-link" href="#contact">Get to know your closing partner <ArrowUpRight size={18}/></a></div></div></section>
      <section className="section container area-grid" id="service-area"><div><p className="eyebrow">03 / PROUDLY SERVING NEW JERSEY</p><h2>One state.<br/>21 counties.<br/><em>Your next address.</em></h2><p className="area-copy">From North Jersey to the Shore and throughout South Jersey, our focus is the same: attentive title and closing support for your next move.</p></div><div className="area-card"><MapPin size={33} strokeWidth={1.4}/><h3>Statewide reach.<br/>Personal attention.</h3><p>Serving buyers, sellers, agents, and lenders in every New Jersey county.</p><div className="counties">{['Atlantic','Bergen','Burlington','Camden','Cape May','Cumberland','Essex','Gloucester','Hudson','Hunterdon','Mercer','Middlesex','Monmouth','Morris','Ocean','Passaic','Salem','Somerset','Sussex','Union','Warren'].map(county=><span key={county}>{county}</span>)}</div></div></section>
      <section className="cta"><div className="container cta-content"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>Move forward.<br/><em>We’ll mind the details.</em></h2></div><a href="#contact" className="button light">Connect with Preferred <ArrowUpRight size={20}/></a></div></section>
      <section className="section container contact-grid" id="contact"><div><p className="eyebrow">04 / LET’S CONNECT</p><h2>A good closing starts<br/>with a conversation.</h2><p>Buying, selling, or refinancing? Tell us about your property and your plans. We look forward to learning about your next move.</p></div><div className="contact-card"><p className="contact-label">REACH OUR TEAM DIRECTLY</p>{['lucas','elliot'].map(name=><a className="email-link" href={`mailto:${name}@preferredtitlecompany.com`} key={name}><Mail size={23} strokeWidth={1.4}/><span><strong>{name[0].toUpperCase()+name.slice(1)}</strong><span>{name}@preferredtitlecompany.com</span></span><ArrowUpRight size={20}/></a>)}<div className="website-label">Our online home<span>preferredtitlecompany.com</span></div></div></section>
    </main>
    <footer><div className="container footer-top"><a className="brand" href="#"><span className="brand-mark">P<span>.</span></span><span className="brand-type">PREFERRED<span>TITLE COMPANY LLC</span></span></a><nav aria-label="Footer navigation">{links.map(([title,href])=><a href={href} key={href}>{title}</a>)}<a href="#contact">Contact</a></nav></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Preferred Title Company LLC. All rights reserved.</span><span>New Jersey, from first step to final signature.</span></div></footer>
  </>;
}
